<form id="task-form" action="/task/index/saveincart/" method="post">
    <h2>Additional information</h2>
<ul class="form-list">
    <li class="task-time">
        <label for="time_id" class="required"><em>*</em>Time for delivery</label>
        <div class="input-box">
            <?php $time = $this->createTimeRange('7:30', '17:30', '30 mins'); ?>
            <select name="time_id" id="time" class="validate-select" title="Time for delivery">
                <?php foreach($time as $v) : ?>
                    <option value="<?php echo $v; ?>" <?php if($v == $this->getFieldValue('time_id')): ?> selected <?php endif; ?>><?php echo $v; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li class="task-day">
        <label for="days_id" class="required"><em>*</em>Accessible days for order</label>
        <div class="input-box">
            <?php $days = $this->getDays(); ?>
            <select name="days_id" id="days" class="validate-select" title="Accessible days for order">
                <?php foreach($days as $k => $v) : ?>
                    <option value="<?php echo $k; ?>" <?php if($k == $this->getFieldValue('days_id')): ?> selected <?php endif; ?>><?php echo $v; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li class="task-code">
        <label for="intercom_code">Intercom code</label>
        <div class="input-box">
            <input class="input-text validate-digits" type="text" id="intercome_code" name="intercome_code" value="<?php echo $this->getFieldValue('intercome_code') ?>">
        </div>
    </li>

    <div class="button-wrapper">
        <button type="button" title="Apply" class="button2" onclick="taskForm.submit(false)" value="Apply"><span><span>Apply</span></span></button>
    </div>
</ul>
</form>
<script type="text/javascript">
    var taskForm = new VarienForm('task-form');
    taskForm.submit = function () {

        return VarienForm.prototype.submit.bind(taskForm)();
    }
</script>
